#!/usr/bin/env bash
make -B amiko
#make bundleAmiko
make -B comed
scp build/outputs/apk/amiko/release/AmiKo-Android-amiko-release.apk zeno@192.168.0.166:/home/ftp/
scp build/outputs/apk/comed/release/AmiKo-Android-comed-release.apk zeno@192.168.0.166:/home/ftp/
#apkup --key amiko.json --apk ./build/outputs/apk/amiko/release/AmiKo-Android-amiko-release.apk
#apkup --key amiko.json --apk ./build/outputs/apk/comed/release/AmiKo-Android-comed-release.apk
