name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
      - name: Setup credentails
        env: # Or as an environment variable
          HIN_CLIENT_ID: ${{ secrets.HIN_CLIENT_ID }}
          HIN_CLIENT_SECRET: ${{ secrets.HIN_CLIENT_SECRET }}
          CERTIFACTION_SERVER: ${{ secrets.CERTIFACTION_SERVER }}
          CERTIFACTION_TEST_SERVER: ${{ secrets.CERTIFACTION_TEST_SERVER }}
        run: |
          sed "s/YOUR_HIN_CLIENT_ID/$HIN_CLIENT_ID/;s/YOUR_HIN_CLIENT_SECRET/$HIN_CLIENT_SECRET/;s#YOUR_CERTIFACTION_SERVER#$CERTIFACTION_SERVER#;s#YOUR_CERTIFACTION_TEST_SERVER#$CERTIFACTION_TEST_SERVER#" ./src/main/java/com/ywesee/amiko/hinclient/HINClientCredentials.java.sample > ./src/main/java/com/ywesee/amiko/hinclient/HINClientCredentials.java
      - name: Build
        run: |
          make comed
          make amiko
          make bundle
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_amiko
        with:
          releaseDirectory: build/outputs/bundle/amikoRelease
          signingKeyBase64: ${{ secrets.STORE_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_comed
        with:
          releaseDirectory: build/outputs/bundle/comedRelease
          signingKeyBase64: ${{ secrets.STORE_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          retention-days: 5
          path: |
            build/outputs/bundle/comedRelease/AmiKo-Android-comed-release.aab
            build/outputs/bundle/amikoRelease/AmiKo-Android-amiko-release.aab
            ${{ steps.sign_amiko.signedReleaseFile }}
            ${{ steps.sign_comed.signedReleaseFile }}
