name: Publish Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Archive
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
      - name: Setup credentails
        env: # Or as an environment variable
          HIN_CLIENT_ID: ${{ secrets.HIN_CLIENT_ID }}
          HIN_CLIENT_SECRET: ${{ secrets.HIN_CLIENT_SECRET }}
          CERTIFACTION_SERVER: ${{ secrets.CERTIFACTION_SERVER }}
          CERTIFACTION_TEST_SERVER: ${{ secrets.CERTIFACTION_TEST_SERVER }}
        run: |
          sed "s/YOUR_HIN_CLIENT_ID/$HIN_CLIENT_ID/;s/YOUR_HIN_CLIENT_SECRET/$HIN_CLIENT_SECRET/;s#YOUR_CERTIFACTION_SERVER#$CERTIFACTION_SERVER#;s#YOUR_CERTIFACTION_TEST_SERVER#$CERTIFACTION_TEST_SERVER#" ./src/main/java/com/ywesee/amiko/hinclient/HINClientCredentials.java.sample > ./src/main/java/com/ywesee/amiko/hinclient/HINClientCredentials.java
      - name: Build
        run: |
          make bundle
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            build/outputs/bundle/comedRelease
            build/outputs/bundle/amikoRelease
